networks:
  notifications-dev:
    driver: bridge

services:
  notificationservice.api:
    container_name: notifications-service
    build:
      context: .
      dockerfile: NotificationService.Api/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - notifications-dev
    depends_on:
      - mongo.db
  mongo.db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - notifications-dev
    volumes:
      - "mongo-data:/data/db"
volumes:
  mongo-data:
