networks:
  notifications-dev:
    driver: bridge

services:
  notificationservice.api:
    container_name: notifications-service
    build:
      context: .
      dockerfile: NotificationService.Api/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - notifications-dev
    volumes:
      - logs-volume:/logs/notification-service
    depends_on:
      - mongo.db
      - rabbit.mq
  mongo.db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - notifications-dev
    volumes:
      - "mongo-data:/data/db"
  rabbit.mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notifications-dev
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  elasticsearch:
    image: elasticsearch:8.19.17
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - notifications-dev
  kibana:
    image: kibana:8.19.17
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - notifications-dev
  logstash:
    image: logstash:8.19.17
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logs-volume:/logs/notification-service
    depends_on:
      - elasticsearch
    networks:
      - notifications-dev
volumes:
  logs-volume:
  mongo-data:
  rabbitmq-data:
