input {
  file {
    path => "/logs/notification-service/*.json"
    codec => json
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  mutate {
    remove_field => ["@version", "host", "path", "tags", "log", "event"]
  }

  if [Level] =~ /^\d+$/ {
    mutate {
      replace => { "Level" => "%{Level}" }
    }
  }

  rename => { "Level" => "level" }

  if [Provider] == "Email" {
    mutate { add_tag => ["email"] }
  }
  if [Provider] == "Telegram" {
    mutate { add_tag => ["telegram"] }
  }
  if [level] == "Error" {
    mutate { add_tag => ["error"] }
  }

  if [RequestPath] =~ /\/health/ {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "notification-service-%{+YYYY.MM.dd}"
    template_enabled => false
  }
  stdout { codec => rubydebug }
}